project:
  type: book
  output-dir: docs

book:
  title: "Spieltheorie und Verhaltensökonomik"
  subtitle: "Sommersemester 2025" 
  author: "Prof. Dr. Jan S. Voßwinkel"
  language:  _language.yml
  repo-url: https://github.com/janvoss/Spieltheorie.git
#  date: "18.3.2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Rationalitaet.qmd
    - Spieltheorie.qmd
    - Verhaltensoekonomik.qmd
    - Literatur.qmd
    - Uebungsaufgaben.qmd

bibliography: Spieltheorie.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-overflow: wrap
    
  pdf:
    documentclass: scrreprt

editor: source

