# Verhaltensökonomik

## Einleitung

## Unrealistische Annahmen vs. realistische Modellierung

```{r}
#| message: false
#| warning: false

library(tidyverse)


set.seed(123)
Anzahl <- 150

df <- data.frame(Farbe=c(rep("rot", Anzahl), rep("blau", Anzahl))
) %>% mutate(x=(ifelse(Farbe=="rot", 0, 1)),
              y=0)
# head(df)

df %>% ggplot(aes(x,y, color=Farbe))+
geom_jitter(width= 1.3, alpha=.5, size=3)+
scale_color_manual(values=c("blue", "red"))+
theme_void()+
labs(title="Rote und blaue Punkte",
     caption="Abbildung: Jan S. Voßwinkel")
```

Und jetzt reden wir über @Musgrave81

## Flat-Rate Bias

## Die Prospect Theory

## Mental Accounting

## Der Status-quo Bias

## Umgang mit Risiken

### Erwartungsnutzentheorie 

- Erwartungswert als Kriterium unplausibel: St. Petersburg Paradox 

- Stattdessen: Erwartungsnutzen
- Nutzen des Erwartunswerts $\neq$ Erwartungswert des Nutzens ($U(EW)\neq EW(U)$)

- Axiome der Erwartungsnutzentheorie:

  - **Vollständigkeit**: FÜr alle Alternativen $A$ und $B$ gilt entweder $A \succeq B$ oder $A \preceq B$ oder beide Bedingungen
  
  - **Transitivität**: Aus $A \preceq B$ und $B \preceq C$ folgt $A \preceq C$
  
  - **Stetitgkeit**: Für alle Alternativen $A, B, C$ mit $A \preceq B$ und $B \preceq C$ existiert eine Wahrscheinlichkeit $p$, sodass gilt $pA+(1-p)C \sim B$
  
  - **Unabhängigkeit**: Für alle Alternativen $A, B, C$ mit $A \preceq B$ gilt $pA+(1-p)C \preceq pB+(1-p)C$ 



### Allais-Paradoxon




## Kritische Diskussion der Verhaltensökonomik